# Generated by Django 5.1.3 on 2024-11-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('channel_title', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('thumbnail_url', models.URLField()),
            ],
        ),
    ]
