# Generated by Django 5.1.3 on 2024-11-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='ArticleVid',
        ),
    ]
