# Generated by Django 5.1.3 on 2024-11-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=255, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('profile_image', models.URLField(max_length=500)),
                ('channel_url', models.URLField(max_length=500)),
                ('text_display', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('like_count', models.IntegerField()),
                ('viewer_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('can_rate', models.BooleanField()),
                ('replies_count', models.IntegerField()),
            ],
        ),
    ]
