# Generated by Django 5.1.3 on 2024-11-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecom',
            name='token_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
