# Generated by Django 5.1.3 on 2024-11-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_articlecom_token_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecom',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
    ]
